---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nydus-snapshotter-sa
  namespace: nydus-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nydus-snapshotter-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nydus-snapshotter-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nydus-snapshotter-role
subjects:
- kind: ServiceAccount
  name: nydus-snapshotter-sa
  namespace: nydus-system

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nydus-snapshotter-configs
  labels:
    app: nydus-snapshotter
  namespace: nydus-system
data:
  FS_DRIVER: "fusedev"
  ENABLE_CONFIG_FROM_VOLUME: "true"
  ENABLE_RUNTIME_SPECIFIC_SNAPSHOTTER: "false"
  ENABLE_SYSTEMD_SERVICE: "false"
  # Snapshotter config
  config.toml: |-
    # Union configured config.toml
    #
    version = 1
    # Snapshotter's own home directory where it stores and creates necessary resources
    root = "/var/lib/containerd/io.containerd.snapshotter.v1.nydus"
    # The snapshotter's GRPC server socket, containerd will connect to plugin on this socket
    address = "/run/containerd-nydus/containerd-nydus-grpc.sock"
    # The nydus daemon mode can be one of the following options: multiple, dedicated, shared, or none.
    # If `daemon_mode` option is not specified, the default value is multiple.
    daemon_mode = "multiple"
    # Whether snapshotter should try to clean up resources when it is closed
    cleanup_on_close = false

    [system]
    # Snapshotter's debug and trace HTTP server interface
    enable = true
    # Unix domain socket path where system controller is listening on
    address = "/run/containerd-nydus/system.sock"

    [system.debug]
    # Snapshotter can profile the CPU utilization of each nydusd daemon when it is being started.
    # This option specifies the profile duration when nydusd is downloading and uncomproessing data.
    daemon_cpu_profile_duration_secs = 5
    # Enable by assigning an address, empty indicates pprof server is disabled
    pprof_address = ""

    [daemon]
    # Specify a configuration file for nydusd
    nydusd_config = "/etc/nydus/nydusd-config.json"
    nydusd_path = "/usr/local/bin/nydusd"
    nydusimage_path = "/usr/local/bin/nydus-image"
    # The fs driver can be one of the following options: fusedev, fscache, blockdev, proxy, or nodev.
    # If `fs_driver` option is not specified, the default value is fusedev.
    fs_driver = "fusedev"
    # How to process when daemon dies: "none", "restart" or "failover"
    recover_policy = "restart"
    # Nydusd worker thread number to handle FUSE or fscache requests, [0-1024].
    # Setting to 0 will use the default configuration of nydusd.
    threads_number = 4
    # Log rotation size for nydusd, in unit MB(megabytes). (default 100MB)
    log_rotation_size = 100

    [cgroup]
    # Whether to use separate cgroup for nydusd.
    enable = true
    # The memory limit for nydusd cgroup, which contains all nydusd processes.
    # Percentage is supported as well, please ensure it is end with "%".
    # The default unit is bytes. Acceptable values include "209715200", "200MiB", "200Mi" and "10%".
    memory_limit = ""

    [log]
    # Print logs to stdout rather than logging files
    log_to_stdout = true
    # Snapshotter's log level
    level = "debug"
    log_rotation_compress = true
    log_rotation_local_time = true
    # Max number of days to retain logs
    log_rotation_max_age = 7
    log_rotation_max_backups = 5
    # In unit MB(megabytes)
    log_rotation_max_size = 100

    [metrics]
    # Enable by assigning an address, empty indicates metrics server is disabled
    address = ":9110"

    [remote]
    convert_vpc_registry = false

    [remote.mirrors_config]
    # Snapshotter will overwrite daemon's mirrors configuration
    # if the values loaded from this driectory are not null before starting a daemon.
    # Set to "" or an empty directory to disable it.
    #dir = "/etc/nydus/certs.d"

    [remote.auth]
    # Fetch the private registry auth by listening to K8s API server
    enable_kubeconfig_keychain = false
    # synchronize `kubernetes.io/dockerconfigjson` secret from kubernetes API server with specified kubeconfig (default `$KUBECONFIG` or `~/.kube/config`)
    kubeconfig_path = ""
    # Fetch the private registry auth as CRI image service proxy
    enable_cri_keychain = false
    # the target image service when using image proxy
    image_service_address = "/run/containerd/containerd.sock"

    [snapshot]
    # Let containerd use nydus-overlayfs mount helper
    enable_nydus_overlayfs = false
    # Path to the nydus-overlayfs binary or name of the binary in $PATH
    nydus_overlayfs_path = "nydus-overlayfs"
    # Insert Kata Virtual Volume option to `Mount.Options`
    enable_kata_volume = false
    # Whether to remove resources when a snapshot is removed
    sync_remove = false

    [cache_manager]
    # Disable or enable recyclebin
    disable = false
    # How long to keep deleted files in recyclebin
    gc_period = "24h"
    # Directory to host cached files
    cache_dir = ""

    [image]
    public_key_file = ""
    validate_signature = false

    # The configuraions for features that are not production ready
    [experimental]
    # Whether to enable stargz support
    enable_stargz = false
    # Whether to enable referrers support
    # The option enables trying to fetch the Nydus image associated with the OCI image and run it.
    # Also see https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-referrers
    enable_referrer_detect = false
    # Whether to enable authentication support
    # The option enables nydus snapshot to provide backend information to nydusd.
    enable_backend_source = false
    [experimental.tarfs]
    # Whether to enable nydus tarfs mode. Tarfs is supported by:
    # - The EROFS filesystem driver since Linux 6.4
    # - Nydus Image Service release v2.3
    enable_tarfs = false
    # Mount rafs on host by loopdev and EROFS
    mount_tarfs_on_host = false
    # Only enable nydus tarfs mode for images with `tarfs hint` label when true
    tarfs_hint = false
    # Maximum of concurrence to converting OCIv1 images to tarfs, 0 means default
    max_concurrent_proc = 0
    # Mode to export tarfs images:
    # - "none" or "": do not export tarfs
    # - "layer_verity_only": only generate disk verity information for a layer blob
    # - "image_verity_only": only generate disk verity information for all blobs of an image
    # - "layer_block": generate a raw block disk image with tarfs for a layer
    # - "image_block": generate a raw block disk image with tarfs for an image
    # - "layer_block_with_verity": generate a raw block disk image with tarfs for a layer with dm-verity info
    # - "image_block_with_verity": generate a raw block disk image with tarfs for an image with dm-verity info
  # Daemon config
  nydusd-config.json: |-
    {
      "device": {
        "backend": {
          "type": "localfs",
          "config": {
            "dir": "/data/nydus/registry"
          }
        },
        "cache": {
          "type": "blobcache",
          "config": {
            "work_dir": "/data/nydus/cache"
          }
        }
      },
      "mode": "direct",
      "digest_validate": false,
      "iostats_files": false,
      "enable_xattr": true,
      "amplify_io": 1048576,
      "fs_prefetch": {
        "enable": true,
        "threads_count": 8,
        "merging_size": 1048576,
        "prefetch_all": true
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nydus-snapshotter
  namespace: nydus-system
  labels:
    app: nydus-snapshotter
spec:
  selector:
    matchLabels:
      app: nydus-snapshotter
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nydus-snapshotter
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: nydus-snapshotter-sa
      # hostNetwork: false # gcsfuse does not allow hostNetwork: true
      hostPID: true
      containers:
      - name: nydus-snapshotter
        image: "ghcr.io/containerd/nydus-snapshotter:latest"
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FS_DRIVER
            valueFrom:
              configMapKeyRef:
                name: nydus-snapshotter-configs
                key: FS_DRIVER
                optional: true
          - name: ENABLE_CONFIG_FROM_VOLUME
            valueFrom:
              configMapKeyRef:
                name: nydus-snapshotter-configs
                key: ENABLE_CONFIG_FROM_VOLUME
                optional: true
          - name: ENABLE_RUNTIME_SPECIFIC_SNAPSHOTTER
            valueFrom:
              configMapKeyRef:
                name: nydus-snapshotter-configs
                key: ENABLE_RUNTIME_SPECIFIC_SNAPSHOTTER
                optional: true
          - name: ENABLE_SYSTEMD_SERVICE
            valueFrom:
              configMapKeyRef:
                name: nydus-snapshotter-configs
                key: ENABLE_SYSTEMD_SERVICE
                optional: true
        lifecycle:
          preStop:
            exec:
              command:
              - "bash"
              - "-c"
              - |
                /opt/nydus-artifacts/opt/nydus/snapshotter.sh cleanup
        command:
         - bash
         - -c
         - |-
           /opt/nydus-artifacts/opt/nydus/snapshotter.sh deploy
        volumeMounts:
        - name: config-volume
          mountPath: "/etc/nydus-snapshotter"
        - name: nydus-lib
          mountPath: "/var/lib/containerd/io.containerd.snapshotter.v1.nydus"
          # mountPropagation: Bidirectional
        - name: nydus-run
          mountPath: "/run/containerd-nydus"
          mountPropagation: Bidirectional
        # - name: nydus-opt
        #   mountPath: "/opt/nydus"
        #   mountPropagation: Bidirectional
        - name: nydus-etc
          mountPath: "/etc/nydus"
          # mountPropagation: Bidirectional
        - name: containerd-conf
          mountPath: "/etc/containerd/"
        - name: containerd-socket
          mountPath: /run/containerd/containerd.sock
        - name: etc-systemd-system
          mountPath: "/etc/systemd/system/"
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data/nydus/registry
        - name: nydus-cache
          mountPath: /data/nydus/cache
        securityContext:
          privileged: true
      volumes:
      - name: config-volume
        configMap:
          name: nydus-snapshotter-configs
      - name: nydus-run
        hostPath:
          path: /run/containerd-nydus
          type: DirectoryOrCreate
      - name: nydus-lib
        emptyDir: {}
        # hostPath:
        #   path: /var/lib/containerd/io.containerd.snapshotter.v1.nydus
        #   type: DirectoryOrCreate
      # - name: nydus-opt
      #   emptyDir: {}
      - name: nydus-etc
        configMap:
          name: nydus-snapshotter-configs
          items:
          - key: config.toml
            path: config.toml
          - key: nydusd-config.json
            path: nydusd-config.json
      - name: containerd-conf
        hostPath:
          path: /etc/containerd/
      # Original containerd nydus mount the host path /usr/local/bin. I don't understand why
      # It appears to be making assumptions as to what binaries exist and can be executed.
      # - name: local-bin
      #   emptyDir: {}
      - name: containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
          type: Socket
      - name: etc-systemd-system
        hostPath:
          path: /etc/systemd/system/
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: mike-test-fuse-load-test-gcp-uc-us-east-2
            mountOptions: "implicit-dirs"
      - name: nydus-cache
        emptyDir: {}
