#!/usr/bin/env python

import argparse
import sys
import copy
import toml


def deep_merge(source, destination):
    for key, value in source.items():
        if isinstance(value, dict):
            node = destination.setdefault(key, {})
            deep_merge(value, node)
        else:
            destination[key] = value
    return destination


def update_toml_config(config_path, output_path):
    # Read the existing TOML file
    try:
        with open(config_path, "r") as f:
            config = toml.load(f)
    except FileNotFoundError:
        print(f"Error: Config file not found: {config_path}", file=sys.stderr)
        sys.exit(1)
    except toml.TomlDecodeError:
        print(f"Error: Invalid TOML file: {config_path}", file=sys.stderr)
        sys.exit(1)

    # Define the Nydus-specific configuration
    nydus_config = {
        "proxy_plugins": {
            "nydus": {
                "type": "snapshot",
                "address": "/run/containerd-nydus/containerd-nydus-grpc.sock"
            }
        },
        "plugins": {
            "io.containerd.grpc.v1.cri": {
                "containerd": {
                    "discard_unpacked_layers": False,
                    "disable_snapshot_annotations": False,
                    "snapshotter": "nydus"
                }
            }
        }
    }

    # Perform a deep merge of the configurations
    updated_config = deep_merge(nydus_config, copy.deepcopy(config))

    # Write the updated configuration
    try:
        if output_path:
            with open(output_path, "w") as f:
                toml.dump(updated_config, f)
            print(
                f"TOML configuration updated and saved to: {output_path}", file=sys.stderr)
        else:
            print(toml.dumps(updated_config))
    except PermissionError:
        print(
            f"Error: Permission denied when writing to {output_path}", file=sys.stderr)
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Update containerd TOML configuration for Nydus.")
    parser.add_argument("-c", "--config", required=True,
                        help="Path to the Containerd TOML configuration file.")
    parser.add_argument(
        "-o", "--output", help="Path to the output file. If not specified, print to stdout.")
    args = parser.parse_args()

    update_toml_config(args.config, args.output)


if __name__ == "__main__":
    main()
